import torch
from transformers import BertTokenizer, TFBertModel

import matplotlib.pyplot as plt


def get_bert_embedding(input_text: str):
    """Returns the embedding of the input text generated by BERT.

    Args:
        input_text (str): The text for which to generate the embedding.
    """    

    tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
    model = TFBertModel.from_pretrained("bert-base-uncased")

